#!/bin/sh

wan="enp11s0f0"
lan="enp11s0f1" 

# Включаем форвардинг пакетов статически, если выключен
if [ $(cat /proc/sys/net/ipv4/ip_forward) = 0 ]
then
  sed -i 's/#net.ipv4.ip_forward/net.ipv4.ip_forward/g' /etc/sysctl.d/99-sysctl.conf
  sysctl -w net.ipv4.ip_forward=1
fi

# Очистка действующих правил
iptables -t nat -F
iptables -t mangle -F
iptables -F
iptables -X
service netfilter-persistent flush

# Блокировать все
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

# Разрешить траффик на lo
iptables -A INPUT -i lo -j ACCEPT
iptables -A OUTPUT -o lo -j ACCEPT

# Разрешить доступ из внутренней сети наружу
iptables -A FORWARD -i $lan -o $wan -j ACCEPT

# Включаем NAT

# Получить текущий глобальный IP адрес
global="$(ifconfig $(echo $wan) | grep -oP 'inet \K\S+')"

for ip in $(cat ip.list)
do
iptables -t nat -A POSTROUTING -o $wan -s $ip -j SNAT --to-source $global 
done

# Разрешаем ответы из внешней сети
iptables -A FORWARD -i $wan -m state --state ESTABLISHED,RELATED -j ACCEPT

# Запрещаем доступ снаружи во внутреннюю сеть
iptables -A FORWARD -i $wan -o $lan -j REJECT

# Разрешить ping
iptables -A INPUT -p icmp --icmp-type 0 -j ACCEPT
iptables -A INPUT -p icmp --icmp-type 8 -j ACCEPT
iptables -A OUTPUT -p icmp -j ACCEPT

# Разрешить SSH
iptables -A INPUT -p tcp --dport 5538 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -p tcp --sport 5538 -m state --state ESTABLISHED -j ACCEPT

# Внешний DNS через TLS
iptables -A INPUT -i $wan -p tcp --sport 853 -m state --state ESTABLISHED -j ACCEPT
iptables -A OUTPUT -o $wan -p tcp --dport 853 -m state --state NEW,ESTABLISHED -j ACCEPT

# Разрешить локальный DNS
iptables -A INPUT -i $lan -p udp --dport 53 -j ACCEPT
iptables -A OUTPUT -o $lan -p udp --sport 53 --dport 1024:65535 -j ACCEPT
iptables -t nat -A PREROUTING -i $lan -p udp -m udp --dport 53 -j DNAT --to-destination 10.1.2.1:53 

# Разрешить DHCP 
iptables -A INPUT -i $lan -p udp --sport 68 --dport 67 -j ACCEPT
iptables -A OUTPUT -o $lan -p udp --sport 67 --dport 68 -j ACCEPT

# Разрешить исходящий HTTP
iptables -A INPUT -i $wan -p tcp --sport 80 -m state --state ESTABLISHED -j ACCEPT
iptables -A OUTPUT -o $wan -p tcp --dport 80 -m state --state NEW,ESTABLISHED -j ACCEPT

# Разрешить исходящий HTTPS
iptables -A INPUT -i $wan -p tcp --sport 443 -m state --state ESTABLISHED -j ACCEPT
iptables -A OUTPUT -o $wan -p tcp --dport 443 -m state --state NEW,ESTABLISHED -j ACCEPT

# Разрешить вхродящие подключения к прокси
iptables -A INPUT -i $lan -p tcp --dport 8080 -m state --state NEW,ESTABLISHED -j ACCEPT
iptables -A OUTPUT -o $lan -p tcp --sport 8080 -m state --state ESTABLISHED -j ACCEPT

# Лог
iptables -N LOGGING
iptables -A OUTPUT -j LOGGING
iptables -A LOGGING -m limit --limit 2/min -j LOG --log-prefix "IPTables Packet Dropped: " --log-level 7
iptables -A LOGGING -j DROP

# Сохранить текущую конфигурацию
service netfilter-persistent save 
