#!/bin/sh

wan="enp0s3"
lan="enp0s8" 

# Включаем форвардинг пакетов статически, если выключен
if [ $(cat /proc/sys/net/ipv4/ip_forward) = 0 ]
then
  sed -i 's/#net.ipv4.ip_forward/net.ipv4.ip_forward/g' /etc/sysctl.d/99-sysctl.conf
  sysctl -w net.ipv4.ip_forward=1
fi

# Очистка действующих правил
service netfilter-persistent flush

# Разрешаем траффик на lo
iptables -A INPUT -i lo -j ACCEPT

# Разрешаем доступ из внутренней сети наружу
iptables -A FORWARD -i $lan -o $wan -j ACCEPT

# Включаем NAT

# Получить текущий глобальный IP адрес
global="$(ifconfig $(echo $wan) | grep -oP 'inet addr:\K\S+')"

for ip in $(cat ip.list)
do
iptables -t nat -A POSTROUTING -o $wan -s $ip -j SNAT --to-source $global 
done

# Разрешаем ответы из внешней сети
iptables -A FORWARD -i $wan -m state --state ESTABLISHED,RELATED -j ACCEPT

# Запрещаем доступ снаружи во внутреннюю сеть
iptables -A FORWARD -i $wan -o $lan -j REJECT

# Path MTU Discovering Black Hole
# Фиксим работу NAT в соответствии с меньшим размером
# пакета на внешнем интерфейсе (провайдер использует VPN судя по всему)
# iptables -t mangle -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS --set-mss 1472

# Сохраняем текущую конфигурацию
service netfilter-persistent save 
